### ISSUE TITLE
failed to get Plugin from volumeSpec for volume "ibm-ubiquity-db"

### ISSUE THREAD

**Issue by hunghoang** [IBM/ubiquity-k8s#300]
Hi
I use helm to install IBM Installer for provisioning PV from SAN. 
Env:
- Storage: V5000
- IBM Spectrum: 3.5.0
- IBM Enabler: 2.1.0
- Kubernetes 1.17.3 on Centos 7 (multipath is set up ok)

But I got these below error. Please help!

In the pod: ubiquity-db:
Unable to attach or mount volumes: unmounted volumes=[ibm-ubiquity-db], unattached volumes=[ibm-ubiquity-db ubiquity-token-krv9c]: failed to get Plugin from volumeSpec for volume "ibm-ubiquity-db" err=no volume plugin matched

I can see the volume u_uat_ibm-ubiquity-db is created on V5000 but It is not assigned to host. 
Hostnames are the same in V5000 and Kubernetes.
<img width="639" alt="Screen Shot 2020-03-02 at 12 15 49 PM" src="https://user-images.githubusercontent.com/5298855/75647444-9219fc80-5c7f-11ea-9dd6-685bb02c9394.png">

**Comment by 27149chen** [comment]
@hunghoang , thank you for contacting us, Kubernetes 1.17 is not supported, we can only support 1.10-1.12 for version 2.1.0
In order to support new Kubernetes versions, you are recommended to use CSI driver: https://github.com/IBM/ibm-block-csi-operator
If you still want to use ubiquity, please open pmr in your storage queue.

**Comment by hunghoang** [comment]
Ok thanks @27149chen 
I'll check this. 
Thanks.
