### ISSUE TITLE
Deleting pod has an error on k8s v1.6.1

### ISSUE THREAD

**Issue by YuDaiWang** [IBM/ubiquity-k8s#53]
On my k8s v1.6.1 env, I create a pod using "kubectl create -f scbe_volume_with_pod.yml". After the pod is in running status, I delete the pod using "kubectl delete -f scbe_volume_with_pod.yml". Then u "kubectl get pod --show-all" returns "No resources found". But the volume is still mapped to host on storage, and there is an error "Volume not found" in flexvolume log and "error-backend-not-found-for-volume" in ubiquity log.
<img width="995" alt="qq20170814-0 2x" src="https://user-images.githubusercontent.com/28969890/29264679-95d3323a-8110-11e7-85e0-17fd45056b22.png">

![error](https://user-images.githubusercontent.com/28969890/29264547-2045d1a8-8110-11e7-8b5d-04f9166c814a.jpeg)
The detail log is below:
[ubiquity-flexvolume.txt](https://github.com/IBM/ubiquity-k8s/files/1221705/ubiquity-flexvolume.txt)

**Comment by shay-berman** [comment]
@midoblgsm 
looks like that the bug is in [line 173](https://github.com/IBM/ubiquity-k8s/blob/dev/controller/controller.go#L173)

in case of k8s 1.6 it goes to this else and then the lnPath set to wrong location - Instead of mountRequest.MountPath it set to basename of mountRequest.MountPath (split command).
So the slink created to a wrong place.
Instead of  /var/lib/kubelet/pods/0d63c4dd-812a-11e7-b967-005056b9f233/volumes/ibm~ubiquity/PVC-ID it link to /var/lib/kubelet/pods/0d63c4dd-812a-11e7-b967-005056b9f233/volumes/ibm~ubiquity/WWN

Any reason why there is a split on the InPath?  is this needed for Spectrum Scale?

**Comment by YuDaiWang** [comment]
it is fixed, I verified it on v1.5.6, v1.6.1 and v1.7.1.
